services:
  # --- Serviço do Back-end (nossa API NestJS) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: build
    container_name: pub_system_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - pub_network
    # Esta é a forma correta de carregar todas as variáveis do .env
    env_file:
      - ./.env
      # --- ADICIONE ESTA LINHA ---
    command: npm run start:dev

  # --- Serviço do Banco de Dados PostgreSQL ---
  db:
    image: postgres:15-alpine
    container_name: pub_system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pub_network
    # O container do Postgres também usará as variáveis do .env
    env_file:
      - ./.env

  # --- (Bônus) Serviço do PGAdmin ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pub_system_pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - pub_network
    # O pgAdmin também usará as variáveis do .env
    env_file:
      - ./.env

# --- Declaração das redes e volumes ---
networks:
  pub_network:
    driver: bridge

volumes:
  postgres_data: