version: '3.8'

services:
  # Serviço do Back-end (nossa API NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dependencies # Perfeito para desenvolvimento!
    container_name: pub_system_backend
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - pub_network
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: pub_system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pub_network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  # (Bônus) Serviço do PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pub_system_pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - pub_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

# Define a rede e o volume nomeado para persistir os dados do banco
networks:
  pub_network:
    driver: bridge

volumes:
  postgres_data: