import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDatabaseIndexes1765391239827 implements MigrationInterface {
    name = 'AddDatabaseIndexes1765391239827'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pontos_entrega" DROP CONSTRAINT "FK_ponto_entrega_ambiente_atendimento"`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" DROP CONSTRAINT "FK_ponto_entrega_ambiente_preparo"`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" DROP CONSTRAINT "FK_ponto_entrega_mesa_proxima"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP CONSTRAINT "FK_item_pedido_ambiente_retirada"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP CONSTRAINT "FK_item_pedido_garcom_entrega"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP CONSTRAINT "FK_item_pedido_retirado_por_garcom"`);
        await queryRunner.query(`ALTER TABLE "comanda_agregados" DROP CONSTRAINT "FK_agregado_comanda"`);
        await queryRunner.query(`ALTER TABLE "comandas" DROP CONSTRAINT "FK_comanda_ponto_entrega"`);
        await queryRunner.query(`ALTER TABLE "funcionarios" DROP CONSTRAINT "fk_funcionarios_empresa"`);
        await queryRunner.query(`ALTER TABLE "funcionarios" DROP CONSTRAINT "fk_funcionarios_ambiente"`);
        await queryRunner.query(`ALTER TABLE "turnos_funcionario" DROP CONSTRAINT "FK_turno_evento"`);
        await queryRunner.query(`ALTER TABLE "turnos_funcionario" DROP CONSTRAINT "FK_turno_funcionario"`);
        await queryRunner.query(`ALTER TABLE "sangrias" DROP CONSTRAINT "FK_363c2c9891a7ed129d65484a6b2"`);
        await queryRunner.query(`ALTER TABLE "sangrias" DROP CONSTRAINT "FK_394c0e8c1c7d436db9cb0351ea5"`);
        await queryRunner.query(`ALTER TABLE "sangrias" DROP CONSTRAINT "FK_d30159995ed0c6bb83d989e9e87"`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" DROP CONSTRAINT "FK_72d24fcf7e83a0c2fa4ccf3e33b"`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" DROP CONSTRAINT "FK_ad88632548e78c5fe2a136f54fa"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP CONSTRAINT "FK_315d05477347317e500c76ab851"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP CONSTRAINT "FK_ed394fea8cc946ff7d9b5b0365f"`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP CONSTRAINT "FK_2df797d5e40e519f337118d2cc7"`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP CONSTRAINT "FK_497dc6b4fedac5912eb3d2fffbd"`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP CONSTRAINT "FK_cfef48411b29c88b74bebc80069"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes" DROP CONSTRAINT "fk_avaliacao_cliente"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes" DROP CONSTRAINT "fk_avaliacao_comanda"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pedidos_comanda"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comandas_mesa"`);
        await queryRunner.query(`DROP INDEX "public"."idx_funcionarios_empresa"`);
        await queryRunner.query(`DROP INDEX "public"."idx_funcionarios_ambiente"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movimentacoes_abertura"`);
        await queryRunner.query(`CREATE TABLE "retiradas_itens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "item_pedido_id" uuid NOT NULL, "garcom_id" uuid NOT NULL, "ambiente_id" uuid NOT NULL, "retirado_em" TIMESTAMP NOT NULL DEFAULT now(), "tempo_reacao_minutos" integer, "observacao" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b4d9e4cc8743b8216c7ce3a5d20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."medalhas_tipo_enum" AS ENUM('VELOCISTA', 'MARATONISTA', 'PONTUAL', 'MVP', 'CONSISTENTE', 'ROOKIE')`);
        await queryRunner.query(`CREATE TYPE "public"."medalhas_nivel_enum" AS ENUM('bronze', 'prata', 'ouro')`);
        await queryRunner.query(`CREATE TABLE "medalhas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo" "public"."medalhas_tipo_enum" NOT NULL, "nome" character varying(100) NOT NULL, "descricao" text NOT NULL, "icone" character varying(50) NOT NULL, "nivel" "public"."medalhas_nivel_enum" NOT NULL, "requisitos" jsonb NOT NULL, "ativo" boolean NOT NULL DEFAULT true, "criado_em" TIMESTAMP NOT NULL DEFAULT now(), "atualizado_em" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_29c41ddb6a5b20779a6b0a01ba9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "medalhas_garcons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "funcionario_id" uuid NOT NULL, "medalha_id" uuid NOT NULL, "conquistada_em" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, CONSTRAINT "PK_afeca028159a330687014538a26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "layouts_estabelecimento" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ambiente_id" uuid NOT NULL, "width" integer NOT NULL DEFAULT '1200', "height" integer NOT NULL DEFAULT '800', "backgroundImage" character varying, "gridSize" integer NOT NULL DEFAULT '20', "criadoEm" TIMESTAMP NOT NULL DEFAULT now(), "atualizadoEm" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7de8081074358c3a62689f624e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "canceladoEm"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "responsavel_inicio_id"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "responsavel_pronto_id"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "responsavel_cancelamento_id"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempo_entrega_minutos"`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ALTER COLUMN "empresa_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "UQ_fd1214820b9f05720b26a917630"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "cpf"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "cpf" character varying(14) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "UQ_fd1214820b9f05720b26a917630" UNIQUE ("cpf")`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ALTER COLUMN "quantidade" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempoentregaminutos"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempoentregaminutos" integer`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempo_preparo_minutos"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempo_preparo_minutos" integer`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempo_reacao_minutos"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempo_reacao_minutos" integer`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempo_entrega_final_minutos"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempo_entrega_final_minutos" integer`);
        await queryRunner.query(`ALTER TYPE "public"."pedidos_status_enum" RENAME TO "pedidos_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."pedidos_status_enum" AS ENUM('FEITO', 'EM_PREPARO', 'QUASE_PRONTO', 'PRONTO', 'RETIRADO', 'ENTREGUE', 'CANCELADO', 'DEIXADO_NO_AMBIENTE')`);
        await queryRunner.query(`ALTER TABLE "pedidos" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos" ALTER COLUMN "status" TYPE "public"."pedidos_status_enum" USING "status"::"text"::"public"."pedidos_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pedidos" ALTER COLUMN "status" SET DEFAULT 'FEITO'`);
        await queryRunner.query(`DROP TYPE "public"."pedidos_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP COLUMN "criado_por_tipo"`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD "criado_por_tipo" character varying(20) NOT NULL DEFAULT 'CLIENTE'`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP COLUMN "tempo_total_minutos"`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD "tempo_total_minutos" integer`);
        await queryRunner.query(`ALTER TABLE "comanda_agregados" ALTER COLUMN "ordem" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "comandas" DROP COLUMN "criado_por_tipo"`);
        await queryRunner.query(`ALTER TABLE "comandas" ADD "criado_por_tipo" character varying(20) NOT NULL DEFAULT 'CLIENTE'`);
        await queryRunner.query(`ALTER TABLE "funcionarios" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."funcionarios_status_enum" AS ENUM('ATIVO', 'INATIVO')`);
        await queryRunner.query(`ALTER TABLE "funcionarios" ADD "status" "public"."funcionarios_status_enum" NOT NULL DEFAULT 'INATIVO'`);
        await queryRunner.query(`COMMENT ON COLUMN "turnos_funcionario"."horasTrabalhadas" IS 'Tempo trabalhado em minutos'`);
        await queryRunner.query(`ALTER TABLE "sangrias" ALTER COLUMN "criadoEm" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."aberturas_caixa_status_enum" AS ENUM('ABERTO', 'FECHADO', 'CONFERENCIA')`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ADD "status" "public"."aberturas_caixa_status_enum" NOT NULL DEFAULT 'ABERTO'`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ALTER COLUMN "criadoEm" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ALTER COLUMN "atualizadoEm" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP COLUMN "tipo"`);
        await queryRunner.query(`CREATE TYPE "public"."movimentacoes_caixa_tipo_enum" AS ENUM('ABERTURA', 'VENDA', 'SANGRIA', 'SUPRIMENTO', 'FECHAMENTO')`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD "tipo" "public"."movimentacoes_caixa_tipo_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP COLUMN "formaPagamento"`);
        await queryRunner.query(`CREATE TYPE "public"."movimentacoes_caixa_formapagamento_enum" AS ENUM('DINHEIRO', 'PIX', 'DEBITO', 'CREDITO', 'VALE_REFEICAO', 'VALE_ALIMENTACAO')`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD "formaPagamento" "public"."movimentacoes_caixa_formapagamento_enum"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP COLUMN "comanda_id"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD "comanda_id" character varying`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ALTER COLUMN "criadoEm" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD CONSTRAINT "UQ_2df797d5e40e519f337118d2cc7" UNIQUE ("abertura_caixa_id")`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."fechamentos_caixa_status_enum" AS ENUM('ABERTO', 'FECHADO', 'CONFERENCIA')`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD "status" "public"."fechamentos_caixa_status_enum" NOT NULL DEFAULT 'FECHADO'`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ALTER COLUMN "criadoEm" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_cliente_cpf" ON "clientes" ("cpf") `);
        await queryRunner.query(`CREATE INDEX "idx_item_pedido_status" ON "itens_pedido" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_pedido_data" ON "pedidos" ("data") `);
        await queryRunner.query(`CREATE INDEX "idx_comanda_status" ON "comandas" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_comanda_data_abertura" ON "comandas" ("dataAbertura") `);
        await queryRunner.query(`CREATE INDEX "idx_funcionario_email" ON "funcionarios" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_turno_funcionario_ativo" ON "turnos_funcionario" ("funcionario_id", "ativo") `);
        await queryRunner.query(`CREATE INDEX "idx_movimentacao_data" ON "movimentacoes_caixa" ("data") `);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD CONSTRAINT "chk_quantidade_positiva" CHECK ("quantidade" > 0)`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ADD CONSTRAINT "FK_4c45ed8ec44343f2f94b1c212e4" FOREIGN KEY ("mesa_proxima_id") REFERENCES "mesas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ADD CONSTRAINT "FK_1d3445d603069f5294b1ea4d431" FOREIGN KEY ("ambiente_atendimento_id") REFERENCES "ambientes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ADD CONSTRAINT "FK_b49b5730f407a5a4f1eb871c977" FOREIGN KEY ("ambiente_preparo_id") REFERENCES "ambientes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ADD CONSTRAINT "FK_6ac1ee2694f3d444f34cb5c4f41" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "FK_c11ca83284571d4840e27b997fa" FOREIGN KEY ("ambiente_id") REFERENCES "ambientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "FK_a28676f7112026235fa0f0648ae" FOREIGN KEY ("ponto_entrega_id") REFERENCES "pontos_entrega"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD CONSTRAINT "FK_33c85c6538e5dc530673159b92c" FOREIGN KEY ("ambiente_retirada_id") REFERENCES "ambientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD CONSTRAINT "FK_3bbdbd57bd0a3cb046c5fb40347" FOREIGN KEY ("retirado_por_garcom_id") REFERENCES "funcionarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD CONSTRAINT "FK_1e02e3a1ee45960fe7d96106604" FOREIGN KEY ("garcom_entrega_id") REFERENCES "funcionarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_4608742065d4e9a5d4af2508f4c" FOREIGN KEY ("criado_por_id") REFERENCES "funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_3fffb9aad96e3a132561df14a04" FOREIGN KEY ("entregue_por_id") REFERENCES "funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comanda_agregados" ADD CONSTRAINT "FK_8364d92bed87e480932d1c38501" FOREIGN KEY ("comanda_id") REFERENCES "comandas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comandas" ADD CONSTRAINT "FK_2984edfd9a7f166586082fae74f" FOREIGN KEY ("ponto_entrega_id") REFERENCES "pontos_entrega"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comandas" ADD CONSTRAINT "FK_f45c42043b75b51164429afe13b" FOREIGN KEY ("criado_por_id") REFERENCES "funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "funcionarios" ADD CONSTRAINT "FK_7bb6627315052ff194752287751" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "funcionarios" ADD CONSTRAINT "FK_3f4f865b4d45124a0a871610dff" FOREIGN KEY ("ambiente_id") REFERENCES "ambientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "turnos_funcionario" ADD CONSTRAINT "FK_d6bab954a914991d6dc375fb929" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "turnos_funcionario" ADD CONSTRAINT "FK_6e216d4bdf0767f32c8c8074afa" FOREIGN KEY ("evento_id") REFERENCES "eventos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retiradas_itens" ADD CONSTRAINT "FK_06b0db0736e4cd8db7ef203e8d3" FOREIGN KEY ("item_pedido_id") REFERENCES "itens_pedido"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retiradas_itens" ADD CONSTRAINT "FK_1ae5affc8f0d313a675b592b3b1" FOREIGN KEY ("garcom_id") REFERENCES "funcionarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retiradas_itens" ADD CONSTRAINT "FK_ae569ce80e7952d38354888c800" FOREIGN KEY ("ambiente_id") REFERENCES "ambientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medalhas_garcons" ADD CONSTRAINT "FK_a84576cc6b2d9e3d655ad021379" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medalhas_garcons" ADD CONSTRAINT "FK_368d2f7f018554c1721b43f90c6" FOREIGN KEY ("medalha_id") REFERENCES "medalhas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layouts_estabelecimento" ADD CONSTRAINT "FK_dc1dec68e33be2ae17adb7bb690" FOREIGN KEY ("ambiente_id") REFERENCES "ambientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sangrias" ADD CONSTRAINT "FK_d30159995ed0c6bb83d989e9e87" FOREIGN KEY ("abertura_caixa_id") REFERENCES "aberturas_caixa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sangrias" ADD CONSTRAINT "FK_394c0e8c1c7d436db9cb0351ea5" FOREIGN KEY ("turno_funcionario_id") REFERENCES "turnos_funcionario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sangrias" ADD CONSTRAINT "FK_363c2c9891a7ed129d65484a6b2" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ADD CONSTRAINT "FK_ad88632548e78c5fe2a136f54fa" FOREIGN KEY ("turno_funcionario_id") REFERENCES "turnos_funcionario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ADD CONSTRAINT "FK_72d24fcf7e83a0c2fa4ccf3e33b" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD CONSTRAINT "FK_ed394fea8cc946ff7d9b5b0365f" FOREIGN KEY ("abertura_caixa_id") REFERENCES "aberturas_caixa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD CONSTRAINT "FK_315d05477347317e500c76ab851" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD CONSTRAINT "FK_2df797d5e40e519f337118d2cc7" FOREIGN KEY ("abertura_caixa_id") REFERENCES "aberturas_caixa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD CONSTRAINT "FK_cfef48411b29c88b74bebc80069" FOREIGN KEY ("turno_funcionario_id") REFERENCES "turnos_funcionario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD CONSTRAINT "FK_497dc6b4fedac5912eb3d2fffbd" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes" ADD CONSTRAINT "FK_8301c89eeb07a6f36b1c35ed478" FOREIGN KEY ("comandaId") REFERENCES "comandas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes" ADD CONSTRAINT "FK_d510583fe3fdb55dbbc440bdb9e" FOREIGN KEY ("clienteId") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "avaliacoes" DROP CONSTRAINT "FK_d510583fe3fdb55dbbc440bdb9e"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes" DROP CONSTRAINT "FK_8301c89eeb07a6f36b1c35ed478"`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP CONSTRAINT "FK_497dc6b4fedac5912eb3d2fffbd"`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP CONSTRAINT "FK_cfef48411b29c88b74bebc80069"`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP CONSTRAINT "FK_2df797d5e40e519f337118d2cc7"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP CONSTRAINT "FK_315d05477347317e500c76ab851"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP CONSTRAINT "FK_ed394fea8cc946ff7d9b5b0365f"`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" DROP CONSTRAINT "FK_72d24fcf7e83a0c2fa4ccf3e33b"`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" DROP CONSTRAINT "FK_ad88632548e78c5fe2a136f54fa"`);
        await queryRunner.query(`ALTER TABLE "sangrias" DROP CONSTRAINT "FK_363c2c9891a7ed129d65484a6b2"`);
        await queryRunner.query(`ALTER TABLE "sangrias" DROP CONSTRAINT "FK_394c0e8c1c7d436db9cb0351ea5"`);
        await queryRunner.query(`ALTER TABLE "sangrias" DROP CONSTRAINT "FK_d30159995ed0c6bb83d989e9e87"`);
        await queryRunner.query(`ALTER TABLE "layouts_estabelecimento" DROP CONSTRAINT "FK_dc1dec68e33be2ae17adb7bb690"`);
        await queryRunner.query(`ALTER TABLE "medalhas_garcons" DROP CONSTRAINT "FK_368d2f7f018554c1721b43f90c6"`);
        await queryRunner.query(`ALTER TABLE "medalhas_garcons" DROP CONSTRAINT "FK_a84576cc6b2d9e3d655ad021379"`);
        await queryRunner.query(`ALTER TABLE "retiradas_itens" DROP CONSTRAINT "FK_ae569ce80e7952d38354888c800"`);
        await queryRunner.query(`ALTER TABLE "retiradas_itens" DROP CONSTRAINT "FK_1ae5affc8f0d313a675b592b3b1"`);
        await queryRunner.query(`ALTER TABLE "retiradas_itens" DROP CONSTRAINT "FK_06b0db0736e4cd8db7ef203e8d3"`);
        await queryRunner.query(`ALTER TABLE "turnos_funcionario" DROP CONSTRAINT "FK_6e216d4bdf0767f32c8c8074afa"`);
        await queryRunner.query(`ALTER TABLE "turnos_funcionario" DROP CONSTRAINT "FK_d6bab954a914991d6dc375fb929"`);
        await queryRunner.query(`ALTER TABLE "funcionarios" DROP CONSTRAINT "FK_3f4f865b4d45124a0a871610dff"`);
        await queryRunner.query(`ALTER TABLE "funcionarios" DROP CONSTRAINT "FK_7bb6627315052ff194752287751"`);
        await queryRunner.query(`ALTER TABLE "comandas" DROP CONSTRAINT "FK_f45c42043b75b51164429afe13b"`);
        await queryRunner.query(`ALTER TABLE "comandas" DROP CONSTRAINT "FK_2984edfd9a7f166586082fae74f"`);
        await queryRunner.query(`ALTER TABLE "comanda_agregados" DROP CONSTRAINT "FK_8364d92bed87e480932d1c38501"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_3fffb9aad96e3a132561df14a04"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_4608742065d4e9a5d4af2508f4c"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP CONSTRAINT "FK_1e02e3a1ee45960fe7d96106604"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP CONSTRAINT "FK_3bbdbd57bd0a3cb046c5fb40347"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP CONSTRAINT "FK_33c85c6538e5dc530673159b92c"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "FK_a28676f7112026235fa0f0648ae"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "FK_c11ca83284571d4840e27b997fa"`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" DROP CONSTRAINT "FK_6ac1ee2694f3d444f34cb5c4f41"`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" DROP CONSTRAINT "FK_b49b5730f407a5a4f1eb871c977"`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" DROP CONSTRAINT "FK_1d3445d603069f5294b1ea4d431"`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" DROP CONSTRAINT "FK_4c45ed8ec44343f2f94b1c212e4"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP CONSTRAINT "chk_quantidade_positiva"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movimentacao_data"`);
        await queryRunner.query(`DROP INDEX "public"."idx_turno_funcionario_ativo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_funcionario_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comanda_data_abertura"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comanda_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pedido_data"`);
        await queryRunner.query(`DROP INDEX "public"."idx_item_pedido_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cliente_cpf"`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ALTER COLUMN "criadoEm" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."fechamentos_caixa_status_enum"`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD "status" character varying NOT NULL DEFAULT 'FECHADO'`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" DROP CONSTRAINT "UQ_2df797d5e40e519f337118d2cc7"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ALTER COLUMN "criadoEm" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP COLUMN "comanda_id"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD "comanda_id" uuid`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP COLUMN "formaPagamento"`);
        await queryRunner.query(`DROP TYPE "public"."movimentacoes_caixa_formapagamento_enum"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD "formaPagamento" character varying`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" DROP COLUMN "tipo"`);
        await queryRunner.query(`DROP TYPE "public"."movimentacoes_caixa_tipo_enum"`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD "tipo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ALTER COLUMN "atualizadoEm" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ALTER COLUMN "criadoEm" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."aberturas_caixa_status_enum"`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ADD "status" character varying NOT NULL DEFAULT 'ABERTO'`);
        await queryRunner.query(`ALTER TABLE "sangrias" ALTER COLUMN "criadoEm" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "turnos_funcionario"."horasTrabalhadas" IS NULL`);
        await queryRunner.query(`ALTER TABLE "funcionarios" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."funcionarios_status_enum"`);
        await queryRunner.query(`ALTER TABLE "funcionarios" ADD "status" character varying DEFAULT 'ATIVO'`);
        await queryRunner.query(`ALTER TABLE "comandas" DROP COLUMN "criado_por_tipo"`);
        await queryRunner.query(`ALTER TABLE "comandas" ADD "criado_por_tipo" character varying`);
        await queryRunner.query(`ALTER TABLE "comanda_agregados" ALTER COLUMN "ordem" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP COLUMN "tempo_total_minutos"`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD "tempo_total_minutos" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP COLUMN "criado_por_tipo"`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD "criado_por_tipo" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."pedidos_status_enum_old" AS ENUM('FEITO', 'EM_PREPARO', 'PRONTO', 'ENTREGUE', 'CANCELADO')`);
        await queryRunner.query(`ALTER TABLE "pedidos" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos" ALTER COLUMN "status" TYPE "public"."pedidos_status_enum_old" USING "status"::"text"::"public"."pedidos_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pedidos" ALTER COLUMN "status" SET DEFAULT 'FEITO'`);
        await queryRunner.query(`DROP TYPE "public"."pedidos_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."pedidos_status_enum_old" RENAME TO "pedidos_status_enum"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempo_entrega_final_minutos"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempo_entrega_final_minutos" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempo_reacao_minutos"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempo_reacao_minutos" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempo_preparo_minutos"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempo_preparo_minutos" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" DROP COLUMN "tempoentregaminutos"`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempoentregaminutos" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ALTER COLUMN "quantidade" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "UQ_fd1214820b9f05720b26a917630"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "cpf"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "cpf" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "UQ_fd1214820b9f05720b26a917630" UNIQUE ("cpf")`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ALTER COLUMN "empresa_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "tempo_entrega_minutos" integer`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "responsavel_cancelamento_id" uuid`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "responsavel_pronto_id" uuid`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "responsavel_inicio_id" uuid`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD "canceladoEm" TIMESTAMP`);
        await queryRunner.query(`DROP TABLE "layouts_estabelecimento"`);
        await queryRunner.query(`DROP TABLE "medalhas_garcons"`);
        await queryRunner.query(`DROP TABLE "medalhas"`);
        await queryRunner.query(`DROP TYPE "public"."medalhas_nivel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."medalhas_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "retiradas_itens"`);
        await queryRunner.query(`CREATE INDEX "idx_movimentacoes_abertura" ON "movimentacoes_caixa" ("abertura_caixa_id") `);
        await queryRunner.query(`CREATE INDEX "idx_funcionarios_ambiente" ON "funcionarios" ("ambiente_id") `);
        await queryRunner.query(`CREATE INDEX "idx_funcionarios_empresa" ON "funcionarios" ("empresa_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comandas_mesa" ON "comandas" ("mesaId") `);
        await queryRunner.query(`CREATE INDEX "idx_pedidos_comanda" ON "pedidos" ("comandaId") `);
        await queryRunner.query(`ALTER TABLE "avaliacoes" ADD CONSTRAINT "fk_avaliacao_comanda" FOREIGN KEY ("comandaId") REFERENCES "comandas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes" ADD CONSTRAINT "fk_avaliacao_cliente" FOREIGN KEY ("clienteId") REFERENCES "clientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD CONSTRAINT "FK_cfef48411b29c88b74bebc80069" FOREIGN KEY ("turno_funcionario_id") REFERENCES "turnos_funcionario"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD CONSTRAINT "FK_497dc6b4fedac5912eb3d2fffbd" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fechamentos_caixa" ADD CONSTRAINT "FK_2df797d5e40e519f337118d2cc7" FOREIGN KEY ("abertura_caixa_id") REFERENCES "aberturas_caixa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD CONSTRAINT "FK_ed394fea8cc946ff7d9b5b0365f" FOREIGN KEY ("abertura_caixa_id") REFERENCES "aberturas_caixa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimentacoes_caixa" ADD CONSTRAINT "FK_315d05477347317e500c76ab851" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ADD CONSTRAINT "FK_ad88632548e78c5fe2a136f54fa" FOREIGN KEY ("turno_funcionario_id") REFERENCES "turnos_funcionario"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aberturas_caixa" ADD CONSTRAINT "FK_72d24fcf7e83a0c2fa4ccf3e33b" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sangrias" ADD CONSTRAINT "FK_d30159995ed0c6bb83d989e9e87" FOREIGN KEY ("abertura_caixa_id") REFERENCES "aberturas_caixa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sangrias" ADD CONSTRAINT "FK_394c0e8c1c7d436db9cb0351ea5" FOREIGN KEY ("turno_funcionario_id") REFERENCES "turnos_funcionario"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sangrias" ADD CONSTRAINT "FK_363c2c9891a7ed129d65484a6b2" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "turnos_funcionario" ADD CONSTRAINT "FK_turno_funcionario" FOREIGN KEY ("funcionario_id") REFERENCES "funcionarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "turnos_funcionario" ADD CONSTRAINT "FK_turno_evento" FOREIGN KEY ("evento_id") REFERENCES "eventos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "funcionarios" ADD CONSTRAINT "fk_funcionarios_ambiente" FOREIGN KEY ("ambiente_id") REFERENCES "ambientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "funcionarios" ADD CONSTRAINT "fk_funcionarios_empresa" FOREIGN KEY ("empresa_id") REFERENCES "empresas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comandas" ADD CONSTRAINT "FK_comanda_ponto_entrega" FOREIGN KEY ("ponto_entrega_id") REFERENCES "pontos_entrega"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comanda_agregados" ADD CONSTRAINT "FK_agregado_comanda" FOREIGN KEY ("comanda_id") REFERENCES "comandas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD CONSTRAINT "FK_item_pedido_retirado_por_garcom" FOREIGN KEY ("retirado_por_garcom_id") REFERENCES "funcionarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD CONSTRAINT "FK_item_pedido_garcom_entrega" FOREIGN KEY ("garcom_entrega_id") REFERENCES "funcionarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itens_pedido" ADD CONSTRAINT "FK_item_pedido_ambiente_retirada" FOREIGN KEY ("ambiente_retirada_id") REFERENCES "ambientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ADD CONSTRAINT "FK_ponto_entrega_mesa_proxima" FOREIGN KEY ("mesa_proxima_id") REFERENCES "mesas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ADD CONSTRAINT "FK_ponto_entrega_ambiente_preparo" FOREIGN KEY ("ambiente_preparo_id") REFERENCES "ambientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pontos_entrega" ADD CONSTRAINT "FK_ponto_entrega_ambiente_atendimento" FOREIGN KEY ("ambiente_atendimento_id") REFERENCES "ambientes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
